# settings.yaml

# Data sources
data_sources:
  collision_dataset_url: "https://data.cityofnewyork.us/api/views/h9gi-nx95/rows.csv?accessType=DOWNLOAD"
  collision_dataset_path: "data/motor-vehicle-collisions-crashes.csv"
  holidays_api: "https://date.nager.at/api/v3/PublicHolidays/{year}/US"

# Output settings
output:
  save_collision_dataset_path: "data/motor-vehicle-collisions-{year}-crashes.csv"
  save_holiday_path: "data/holidays-{year}-response.json"
  format: "parquet"

filtration:
  year: 2025

# Logging settings
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "logs/pipeline.log"